# DATA 1 Practical 5

Simos Gerasimou


## All You Need to Know About Google Play Store

**Google Play store** ([https://play.google.com/store?hl=en](https://play.google.com/store?hl=en)) is a digital distribution service operated and developed by Google. It serves as the official app store for the Android operating system, allowing users to browse and download applications developed with the Android software development kit (SDK) and published through Google. [Wikipedia](https://en.wikipedia.org/wiki/Google_Play).

**DataVision** has scraped the Google Play store  and acquired data for several Android applications. Since data from the Play Store apps has great potential to drive app-making businesses to success, DataVision wants to investigate whether any actionable insights can be drawn for developers to work on and capture the Android market!

#### Your tasks are to explore this dataset and generade some actionable knowledge. 


#### This Jupyter Notebook will be presented to  Google stakeholders who have limited knowledge about data science. So, your findings should be complemented by a suitable justification explaining what you observe and, when applicable, what does this observation  mean and, possibly, why it occurs.

* For each question (task) a description is provided accompanied (most of the time) by two cells: one for writing the Python code and another for providing the justification. Feel free to add more cells if you feel they are needed, but keep the cells corresponding to the same question close by.

(1) To answer these exercises, you **must first read Chapter 3: Dapa Manipulation with Pandas from the Python Data Science Handbook** (https://jakevdp.github.io/PythonDataScienceHandbook/03.00-introduction-to-pandas.html)

(2) If you haven't already done so, complete the exercises on Pandas tutorial to become familiar with the library.

**Pandas API Reference**: https://pandas.pydata.org/pandas-docs/stable/reference/index.html

***

### Part 1: Reading dataset

The Google dataset is available on VLE (look for googleplaystore.csv in the Practicals section)

Before doing the tasks below, you may want to explore the dataset using a spreadsheet editor (e.g., Excel) to get a high-level view of the dataset.

**T1) Load the Google Play Store dataset using Pandas**

**Note**: You have to download the dataset on your local machine and then load it onto the Jupyter Notebook

In [1]:
import pandas as pd 
import numpy as np

df = pd.read_csv('googleplaystore.csv')

***

### Part 2: Cleaning and analysing the dataset

**T2i) Print the first 10 records of the dataframe**

In [2]:
df.head(10)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite â€“ FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
5,Paper flowers instructions,ART_AND_DESIGN,4.4,167,5.6M,"50,000+",Free,0,Everyone,Art & Design,"March 26, 2017",1.0,2.3 and up
6,Smoke Effect Photo Maker - Smoke Editor,ART_AND_DESIGN,3.8,178,19M,"50,000+",Free,0,Everyone,Art & Design,"April 26, 2018",1.1,4.0.3 and up
7,Infinite Painter,ART_AND_DESIGN,4.1,36815,29M,"1,000,000+",Free,0,Everyone,Art & Design,"June 14, 2018",6.1.61.1,4.2 and up
8,Garden Coloring Book,ART_AND_DESIGN,4.4,13791,33M,"1,000,000+",Free,0,Everyone,Art & Design,"September 20, 2017",2.9.2,3.0 and up
9,Kids Paint Free - Drawing Fun,ART_AND_DESIGN,4.7,121,3.1M,"10,000+",Free,0,Everyone,Art & Design;Creativity,"July 3, 2018",2.8,4.0.3 and up

**T2ii) Print the last 3 records of the dataframe**

In [3]:
df.tail(3)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10837,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10838,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10839,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

**T3) Get general info about the dataset**

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10840 entries, 0 to 10839
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10840 non-null  object
 1   Category        10840 non-null  object
 2   Rating          9366 non-null   float64
 3   Reviews         10840 non-null  int64
 4   Size            10840 non-null  object
 5   Installs        10840 non-null  object
 6   Type            10839 non-null  object
 7   Price           10840 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10840 non-null  object
 10  Last Updated    10840 non-null  object
 11  Current Ver     10832 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), int64(1), object(11)
memory usage: 1.1+ MB

**T4) Explore the dataset and try to understand the meaning of each column. For each column, write its meaning and its data type**

**T5) Get the shape of the dataframe**

In [5]:
df.shape

(10840, 13)

**T6) Get the name of the columns for the dataframe**

In [6]:
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

**T7) Do you think the columns (variables) need to be more readable? If so, rename them (e.g., suitable capitalisation, eliminate underscores, full words)**

**T8) How many duplicated records exist?**

**Note**: A record is duplicated if all its entries are identical with another record

In [7]:
dup = df[df.duplicated()]
dup

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
229,Quick PDF Scanner + OCR FREE,BUSINESS,4.2,80805,Varies with device,"5,000,000+",Free,0,Everyone,Business,"February 26, 2018",Varies with device,4.0.3 and up
236,Box,BUSINESS,4.2,159872,Varies with device,"10,000,000+",Free,0,Everyone,Business,"July 31, 2018",Varies with device,Varies with device
239,Google My Business,BUSINESS,4.4,70991,Varies with device,"5,000,000+",Free,0,Everyone,Business,"July 24, 2018",2.19.0.204537701,4.4 and up
256,ZOOM Cloud Meetings,BUSINESS,4.4,31614,37M,"10,000,000+",Free,0,Everyone,Business,"July 20, 2018",4.1.28165.0716,4.0 and up
261,join.me - Simple Meetings,BUSINESS,4.0,6989,Varies with device,"1,000,000+",Free,0,Everyone,Business,"July 16, 2018",4.3.0.508,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8643,Wunderlist: To-Do List & Tasks,PRODUCTIVITY,4.6,404610,Varies with device,"10,000,000+",Free,0,Everyone,Productivity,"April 6, 2018",Varies with device,Varies with device
8654,"TickTick: To Do List with Reminder, Day Planner",PRODUCTIVITY,4.6,25370,Varies with device,"1,000,000+",Free,0,Everyone,Productivity,"August 6, 2018",Varies with device,Varies with device
8658,ColorNote Notepad Notes,PRODUCTIVITY,4.6,2401017,Varies with device,"100,000,000+",Free,0,Everyone,Productivity,"June 27, 2018",Varies with device,Varies with device
10049,Airway Ex - Intubate. Anesthetize. Train.,MEDICAL,4.3,123,86M,"10,000+",Free,0,Everyone,Medical,"June 1, 2018",0.6.88,5.0 and up
10767,AAFP,MEDICAL,3.8,63,24M,"10,000+",Free,0,Everyone,Medical,"June 22, 2018",2.3.1,5.0 and up

**T9i) How many of the duplicated records refer to 'blood pressure' in their name?**

In [8]:
# dup contains 0 but df contains 2
contains_bp = df.App.str.contains('blood pressure')
contains_bp.sum()

2

**T9ii) Print the records you found in task T9i**

In [9]:
df[contains_bp]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
2541,Hypertension High blood pressure,MEDICAL,3.8,292,2.7M,"100,000+",Free,0,Everyone,Medical,"April 16, 2018",43.0,4.0.3 and up
6615,Hypertension Hi blood pressure,MEDICAL,3.8,292,2.7M,"100,000+",Free,0,Everyone,Medical,"April 16, 2018",43.0,4.0.3 and up

**T10) Let's look more closely into the dataset. Are there more duplicates?**

**Hint:** Check the duplicated function of Pandas to understand how the function operates. Do you need to specify what information to consider when checking for duplicates?

In [10]:
df[df.duplicated(subset=['App'])]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
229,Quick PDF Scanner + OCR FREE,BUSINESS,4.2,80805,Varies with device,"5,000,000+",Free,0,Everyone,Business,"February 26, 2018",Varies with device,4.0.3 and up
236,Box,BUSINESS,4.2,159872,Varies with device,"10,000,000+",Free,0,Everyone,Business,"July 31, 2018",Varies with device,Varies with device
239,Google My Business,BUSINESS,4.4,70991,Varies with device,"5,000,000+",Free,0,Everyone,Business,"July 24, 2018",2.19.0.204537701,4.4 and up
256,ZOOM Cloud Meetings,BUSINESS,4.4,31614,37M,"10,000,000+",Free,0,Everyone,Business,"July 20, 2018",4.1.28165.0716,4.0 and up
261,join.me - Simple Meetings,BUSINESS,4.0,6989,Varies with device,"1,000,000+",Free,0,Everyone,Business,"July 16, 2018",4.3.0.508,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10714,FarmersOnly Dating,DATING,3.0,1145,1.4M,"100,000+",Free,0,Mature 17+,Dating,"February 25, 2016",2.2,4.0 and up
10719,Firefox Focus: The privacy browser,COMMUNICATION,4.4,36981,4.0M,"1,000,000+",Free,0,Everyone,Communication,"July 6, 2018",5.2,5.0 and up
10729,FP Notebook,MEDICAL,4.5,410,60M,"50,000+",Free,0,Everyone,Medical,"March 24, 2018",2.1.0.372,4.4 and up
10752,Slickdeals: Coupons & Shopping,SHOPPING,4.5,33599,12M,"1,000,000+",Free,0,Everyone,Shopping,"July 30, 2018",3.9,4.4 and up
10767,AAFP,MEDICAL,3.8,63,24M,"10,000+",Free,0,Everyone,Medical,"June 22, 2018",2.3.1,5.0 and up

**T11) Find the app with the highest number of duplicated records and the number of duplicated records for this app**

**Hint:** How can you count the records of a dataframe?

In [11]:
df[df.duplicated(subset=['App'], keep=False)]['App'].value_counts().idxmax()

'ROBLOX'

**T12) Investigate the records for the app you found in task T10. What can you observe? Can you identiy the reason why the duplicate records exist?**

In [12]:
df.loc[df['App'] =='ROBLOX']
# Changes in reviews, category

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
1653,ROBLOX,GAME,4.5,4447388,67M,"100,000,000+",Free,0,Everyone 10+,Adventure;Action & Adventure,"July 31, 2018",2.347.225742,4.1 and up
1701,ROBLOX,GAME,4.5,4447346,67M,"100,000,000+",Free,0,Everyone 10+,Adventure;Action & Adventure,"July 31, 2018",2.347.225742,4.1 and up
1748,ROBLOX,GAME,4.5,4448791,67M,"100,000,000+",Free,0,Everyone 10+,Adventure;Action & Adventure,"July 31, 2018",2.347.225742,4.1 and up
1841,ROBLOX,GAME,4.5,4449882,67M,"100,000,000+",Free,0,Everyone 10+,Adventure;Action & Adventure,"July 31, 2018",2.347.225742,4.1 and up
1870,ROBLOX,GAME,4.5,4449910,67M,"100,000,000+",Free,0,Everyone 10+,Adventure;Action & Adventure,"July 31, 2018",2.347.225742,4.1 and up
2016,ROBLOX,FAMILY,4.5,4449910,67M,"100,000,000+",Free,0,Everyone 10+,Adventure;Action & Adventure,"July 31, 2018",2.347.225742,4.1 and up
2088,ROBLOX,FAMILY,4.5,4450855,67M,"100,000,000+",Free,0,Everyone 10+,Adventure;Action & Adventure,"July 31, 2018",2.347.225742,4.1 and up
2206,ROBLOX,FAMILY,4.5,4450890,67M,"100,000,000+",Free,0,Everyone 10+,Adventure;Action & Adventure,"July 31, 2018",2.347.225742,4.1 and up
4527,ROBLOX,FAMILY,4.5,4443407,67M,"100,000,000+",Free,0,Everyone 10+,Adventure;Action & Adventure,"July 31, 2018",2.347.225742,4.1 and up

**T13) Assuming that the data has been scaped sequentially, remove all duplicates by specifying which record to keep**

**Hint:** You may want to check the documentation of the drop_duplicates function

In [37]:
# keep most recent copy
df.drop_duplicates(subset=['App'], keep='last', inplace=True)

**T14i) Check the type of variable indicating the last timethe application was update and convert it into the appropriate format**

**Hint:** 

* You may want to check https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_datetime.html

* Pay attention to the date format and the month type

* You may also want to check https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.loc.html

In [14]:
df['Last Updated'] = pd.to_datetime(df['Last Updated'])

**T14ii) Which application was updated least recently and when did this happen?**

In [15]:
df.sort_values(by=['Last Updated']).iloc[0]

App               FML F*ck my life + widget
Category                             FAMILY
Rating                                  4.2
Reviews                                1415
Size                                   209k
Installs                           100,000+
Type                                   Free
Price                                     0
Content Rating                     Everyone
Genres                        Entertainment
Last Updated            2010-05-21 00:00:00
Current Ver                             3.1
Android Ver                      1.5 and up
Name: 7479, dtype: object

**T15) How many unique values exist under the Price variable? Print the first five unique prices.**

In [16]:
df.Price.unique()[:5]

array(['0', '$4.99', '$3.99', '$1.49', '$2.99'], dtype=object)

**T16i) Write a function moneyWithoutCurrencySymbol that takes a string and returns the string as a float without the currency symbol (if exists)**

In [17]:
def money_without_currency_symbol(c):
    if isinstance(c, float): return c
    return float(c.replace('$', ''))

**T16ii) Perform the necessary processing tasks to convert the Price variable into a float**

**Hint:**

* You may want to use the function from task T16i
* You may want to check https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.apply.html
* Alternatively, you may want to check https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_numeric.html

In [18]:
df['Price'] = df.aggregate({'Price': money_without_currency_symbol})
df['Price']

0        0.0
2        0.0
3        0.0
4        0.0
5        0.0
        ...
10835    0.0
10836    0.0
10837    0.0
10838    0.0
10839    0.0
Name: Price, Length: 9659, dtype: float64

**T17i) How many missing data exist for each variable? Is this a messy or a clean dataset?**

In [19]:
df.isna().sum()

App                  0
Category             0
Rating            1463
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       0
Genres               0
Last Updated         0
Current Ver          8
Android Ver          2
dtype: int64

**T17ii) Impute the categorical columns with the mode value**

**Hint:** Check Chapter 3 of the Python Data Science Handbook

In [20]:
df.Type = df.Type.fillna(df.mode().iloc[0])
df.Type

0        Free
2        Free
3        Free
4        Free
5        Free
         ...
10835    Free
10836    Free
10837    Free
10838    Free
10839    Free
Name: Type, Length: 9659, dtype: object

**T17iii) What would be an appropriate value to impute for the other variable? Apply the imputation.**

In [21]:
# 0
df.fillna(0)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0.0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up
2,"U Launcher Lite â€“ FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0.0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0.0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0.0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up
5,Paper flowers instructions,ART_AND_DESIGN,4.4,167,5.6M,"50,000+",Free,0.0,Everyone,Art & Design,2017-03-26,1.0,2.3 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10835,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0.0,Everyone,Education,2017-07-25,1.48,4.1 and up
10836,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0.0,Everyone,Education,2018-07-06,1.0,4.1 and up
10837,Parkinson Exercices FR,MEDICAL,0.0,3,9.5M,"1,000+",Free,0.0,Everyone,Medical,2017-01-20,1.0,2.2 and up
10838,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0.0,Mature 17+,Books & Reference,2015-01-19,Varies with device,Varies with device
10839,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0.0,Everyone,Lifestyle,2018-07-25,Varies with device,Varies with device

**T18i) Which are the possible values for the variable Installs?**

In [22]:
pd.unique(df.Installs)

array(['10,000+', '5,000,000+', '50,000,000+', '100,000+', '50,000+',
       '1,000,000+', '10,000,000+', '5,000+', '500,000+',
       '1,000,000,000+', '100,000,000+', '1,000+', '50+', '100+', '500+',
       '10+', '1+', '5+', '500,000,000+', '0+', '0'], dtype=object)

**T18ii) Based on the result from task T18i, do you see any odd value? Do think any cleaning is needed?**

**T18iii) If you did any cleaning in task T18ii, check that the cleaning has taken place**

**T19i) Perform the necessary processing tasks to convert the Size variable into a float using a common metric (i.e., which will enable to compare records between each other using the size value). Set records whose value is "Varies with device" to 1**

In [23]:
def convert_size(x):
    if isinstance(x, float):
        return x
    elif 'M' in x:
         return 1000000 * float(x.replace('M', ''))
    elif 'k' in x:
        return 1000 * float(x.replace('k', ''))
    return None

df['Size'] = df.Size.map(convert_size)

**T19ii) Which is the smallest application and what is its size?**

In [24]:
min(df.Size)

8500.0

**T19iii) What is the most common Category of the largest applications and which applications belong to this Category?**

In [25]:
largest_mean_size = df.groupby('Category')['Size'].mean().idxmax()
df.query('Category == @largest_mean_size')

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
1677,Bubble Witch 3 Saga,GAME,4.7,1732263,78000000.0,"50,000,000+",Free,0.0,Everyone,Puzzle,2018-07-17,4.8.4,3.0 and up
1682,Race the Traffic Moto,GAME,3.8,270687,38000000.0,"10,000,000+",Free,0.0,Teen,Racing,2018-07-20,1.0.16,4.0.3 and up
1691,Marble - Temple Quest,GAME,4.3,42053,24000000.0,"10,000,000+",Free,0.0,Everyone,Puzzle,2018-06-21,4.9,4.0.3 and up
1692,Shooting King,GAME,4.4,257724,69000000.0,"10,000,000+",Free,0.0,Everyone 10+,Sports,2018-05-25,1.4.2,4.0.3 and up
1731,Jungle Marble Blast,GAME,4.3,18985,23000000.0,"5,000,000+",Free,0.0,Everyone,Casual,2018-07-23,1.5.4,4.0.3 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10790,Winter Wonderland,GAME,4.0,1287,38000000.0,"50,000+",Free,0.0,Everyone,Word,2013-12-18,1.0,2.2 and up
10791,Soccer Clubs Logo Quiz,GAME,4.2,21661,16000000.0,"1,000,000+",Free,0.0,Everyone,Trivia,2018-05-24,1.3.81,4.0 and up
10792,Sid Story,GAME,4.4,28510,78000000.0,"500,000+",Free,0.0,Teen,Card,2018-08-01,2.6.6,4.0.3 and up
10802,Fatal Raid - No.1 Mobile FPS,GAME,4.3,56496,81000000.0,"1,000,000+",Free,0.0,Teen,Action,2018-08-07,1.5.447,4.0 and up
10803,Poker Pro.Fr,GAME,4.2,5442,17000000.0,"100,000+",Free,0.0,Teen,Card,2018-05-22,4.1.3,2.3 and up

**T20) Are there any logical errors in the Type and Price variables? Are there any applications whose type if Free and you have to pay? Are there any application with type Paid which you can get for free? Check the integrity of the dataset using these conditions**

In [31]:
df.query("Type == 'Free' & Price != 0 | Type == 'Paid' & Price == 0")

Empty DataFrame
Columns: [App, Category, Rating, Reviews, Size, Installs, Type, Price, Content Rating, Genres, Last Updated, Current Ver, Android Ver, Updated Since]
Index: []

**T21) A reviewer of an application may or may not rate the review. Check the consistency of the dataset concerning this matter**

In [27]:
df.query("Rating.isnull() & Reviews > 1")

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
113,Wrinkles and rejuvenation,BEAUTY,NaN,182,5700000.0,"100,000+",Free,0.0,Everyone 10+,Beauty,2017-09-20,8.0,3.0 and up
123,Manicure - nail design,BEAUTY,NaN,119,3700000.0,"50,000+",Free,0.0,Everyone,Beauty,2018-07-23,1.3,4.1 and up
126,Skin Care and Natural Beauty,BEAUTY,NaN,654,7400000.0,"100,000+",Free,0.0,Teen,Beauty,2018-07-17,1.15,4.1 and up
129,"Secrets of beauty, youth and health",BEAUTY,NaN,77,2900000.0,"10,000+",Free,0.0,Mature 17+,Beauty,2017-08-08,2.0,2.3 and up
130,Recipes and tips for losing weight,BEAUTY,NaN,35,3100000.0,"10,000+",Free,0.0,Everyone 10+,Beauty,2017-12-11,2.0,3.0 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10820,Poop FR,FAMILY,NaN,6,2500000.0,50+,Free,0.0,Everyone,Entertainment,2018-05-29,1.0,4.0.3 and up
10823,Cardio-FR,MEDICAL,NaN,67,82000000.0,"10,000+",Free,0.0,Everyone,Medical,2018-07-31,2.2.2,4.4 and up
10824,Naruto & Boruto FR,SOCIAL,NaN,7,7700000.0,100+,Free,0.0,Teen,Social,2018-02-02,1.0,4.0 and up
10830,payermonstationnement.fr,MAPS_AND_NAVIGATION,NaN,38,9800000.0,"5,000+",Free,0.0,Everyone,Maps & Navigation,2018-06-13,2.0.148.0,4.0 and up
10837,Parkinson Exercices FR,MEDICAL,NaN,3,9500000.0,"1,000+",Free,0.0,Everyone,Medical,2017-01-20,1.0,2.2 and up

**T22) Get some descriptive statistics for the dataset**

In [28]:
df.describe()

            Rating       Reviews          Size        Price
count  8196.000000  9.659000e+03  8.432000e+03  9659.000000
mean      4.173219  2.166512e+05  2.039797e+07     1.097231
std       0.536269  1.830738e+06  2.182817e+07    16.851618
min       1.000000  0.000000e+00  8.500000e+03     0.000000
25%       4.000000  2.500000e+01  4.600000e+06     0.000000
50%       4.300000  9.690000e+02  1.200000e+07     0.000000
75%       4.500000  2.940100e+04  2.800000e+07     0.000000
max       5.000000  7.812821e+07  1.000000e+08   400.000000

**T23) Create a new column that indicates the difference between the Last Updated variable column and the current date.**

In [29]:
df['Updated Since'] = pd.to_datetime('today') - df['Last Updated']
df['Updated Since']

0       1133 days 20:37:05.570725
2        927 days 20:37:05.570725
3        981 days 20:37:05.570725
4        969 days 20:37:05.570725
5       1420 days 20:37:05.570725
                   ...
10835   1299 days 20:37:05.570725
10836    953 days 20:37:05.570725
10837   1485 days 20:37:05.570725
10838   2217 days 20:37:05.570725
10839    934 days 20:37:05.570725
Name: Updated Since, Length: 9659, dtype: timedelta64[ns]

**T24) (Funny) What is weird about the most expensive appslications which are at or above the 99.9th percentile?**

In [36]:
top_quantile = df.quantile(.99)['Price']
df.query('Price >= @top_quantile')

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Updated Since
1838,Star Wars â„¢: DIRTY,GAME,4.5,38207,15000000.0,"100,000+",Paid,9.99,Teen,Role Playing,2015-10-19,1.0.6,4.1 and up,1944 days 20:37:05.570725
2278,CCHT PREP,MEDICAL,3.6,25,266000.0,"1,000+",Paid,10.99,Everyone,Medical,2016-12-08,1.2,2.1 and up,1528 days 20:37:05.570725
2289,Critical Care Paramedic Review,MEDICAL,4.4,17,1800000.0,"1,000+",Paid,9.99,Everyone 10+,Medical,2018-05-14,2.0.5,4.4W and up,1006 days 20:37:05.570725
2294,Number Therapy,MEDICAL,NaN,0,5300000.0,50+,Paid,14.99,Everyone,Medical,2017-10-03,1.0,4.0.3 and up,1229 days 20:37:05.570725
2295,InfantRisk Center HCP,MEDICAL,2.6,41,14000000.0,"1,000+",Paid,9.99,Everyone,Medical,2015-05-06,1.3.4,2.3.3 and up,2110 days 20:37:05.570725
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9917,Eu Sou Rico,FINANCE,NaN,0,1400000.0,0+,Paid,394.99,Everyone,Finance,2018-07-11,1.0,4.0.3 and up,948 days 20:37:05.570725
9934,I'm Rich/Eu sou Rico/Ø£Ù†Ø§ ØºÙ†ÙŠ/æˆ‘å¾ˆæœ‰éŒ¢,LIFESTYLE,NaN,0,40000000.0,0+,Paid,399.99,Everyone,Lifestyle,2017-12-01,MONEY,4.1 and up,1170 days 20:37:05.570725
10006,XCOMÂ®: Enemy Within,FAMILY,4.2,13752,21000000.0,"100,000+",Paid,9.99,Mature 17+,Strategy,2017-10-24,1.7.0,4.0 and up,1208 days 20:37:05.570725
10644,Football Manager Mobile 2018,SPORTS,3.9,11460,NaN,"100,000+",Paid,8.99,Everyone,Sports,2018-06-27,Varies with device,4.1 and up,962 days 20:37:05.570725
10781,Trine 2: Complete Story,GAME,3.8,252,11000000.0,"10,000+",Paid,16.99,Teen,Action,2015-02-27,2.22,5.0 and up,2178 days 20:37:05.570725

### Should you finish earlier/want to practice at home, you could

* Check that the Price variable does not have logical error (values below 0)
* Check that the values of Rating variable is within the limits [0,5]
* Any other analysis that you might could generate some useful insight.